spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loan
  application:
    name: loan-reactive-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#  profiles:
#    active: qa
server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
